export interface SchemaProviderField {
  name: string;
  type: string;
  isId: boolean;
  isRequired: boolean;
  isUnique: boolean;
  isRelation: boolean;
  hasDefault: boolean;
  isAutoGenerated: boolean;
}

export interface ModelSchema {
  name: string;
  fields: SchemaProviderField[];
}

export interface SchemaProvider {
  getModel(modelName: string): Promise<ModelSchema | null>;
  listModels(): Promise<string[]>;
}
