/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-07-07T20:55:46.724Z
 * Framework: nextjs
 * Output: src
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "config": {
    "baseURL": "",
    "basePATH": ""
  },
  "controllers": {
    "example": {
      "name": "Example",
      "description": "",
      "path": "/example",
      "actions": {
        "health": {
          "name": "health",
          "description": "",
          "path": "/health",
          "method": "GET"
        },
        "cacheDemo": {
          "name": "cacheDemo",
          "description": "",
          "path": "/cache/:key",
          "method": "GET"
        },
        "scheduleJob": {
          "name": "scheduleJob",
          "description": "Schedule a background job",
          "path": "/schedule-job",
          "method": "POST"
        }
      }
    }
  },
  "processor": {},
  "handler": {},
  "$context": {},
  "$plugins": {},
  "$caller": {}
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
