/* eslint-disable */
/* prettier-ignore */

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-08-21T12:15:06.500Z
 * Framework: nextjs
 * Output: src/
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "example": {
      "name": "Example",
      "path": "/example",
      "actions": {
        "health": {
          "path": "/health",
          "method": "GET",
          "$Infer": {}
        }
      }
    }
  }
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
