import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: ["src/index.ts"],
    format: ["cjs", "esm"],
    dts: false,
    splitting: false,
    sourcemap: true,
    clean: true,
    treeshake: true,
    external: ["react", "react-dom", "@igniter-js/common"],
  },
  {
    entry: ["src/adapters/index.ts"],
    format: ["cjs", "esm"],
    outDir: "dist/adapters",
    dts: false,
    splitting: false,
    sourcemap: true,
    clean: true,
    treeshake: true,
    external: ["react", "react-dom", "@igniter-js/common"],
  },
  {
    entry: ["src/plugins/index.ts"],
    format: ["cjs", "esm"],
    outDir: "dist/plugins",
    dts: false,
    external: ["@igniter-js/common"],
  },
  {
    entry: ["src/store/index.ts"],
    format: ["cjs", "esm"],
    outDir: "dist/store",
    dts: false,
    splitting: false,
    sourcemap: true,
    clean: true,
    treeshake: true,
    external: ["@igniter-js/store"],
  },
  {
    entry: ["src/telemetry/index.ts"],
    format: ["cjs", "esm"],
    outDir: "dist/telemetry",
    dts: false,
    splitting: false,
    sourcemap: true,
    clean: true,
    treeshake: true,
    external: ["@igniter-js/telemetry", "zod"],
  },
  {
    entry: {
      "igniter.hooks": "src/client/igniter.hooks.ts",
    },
    format: ["esm"],
    dts: false,
    splitting: true,
    outDir: "dist/client",
    external: ["react", "react-dom", "@igniter-js/common"],
  },
  {
    entry: {
      "igniter.context": "src/client/igniter.context.tsx",
    },
    format: ["esm"],
    dts: false,
    splitting: true,
    outDir: "dist/client",
    external: ["react", "react-dom", "@igniter-js/common"],
  },
  {
    entry: {
      index: "src/client/index.ts",
      "index.server": "src/client/index.server.ts",
      "index.browser": "src/client/index.browser.ts",
    },
    format: ["cjs", "esm"],
    dts: false,
    treeshake: true,
    splitting: true,
    outDir: "dist/client",
    external: ["react", "react-dom", "@igniter-js/common"],
  },
]);
