 

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-08-03T16:31:58.427Z
 * Framework: nextjs
 * Output: src/
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "message": {
      "name": "Message",
      "description": "",
      "path": "/messages",
      "actions": {
        "list": {
          "name": "list",
          "description": "List all Messages",
          "path": "/",
          "method": "GET"
        },
        "getById": {
          "name": "getById",
          "description": "Get a Message by ID",
          "path": "/:id",
          "method": "GET"
        },
        "create": {
          "name": "create",
          "description": "Create a new Message",
          "path": "/",
          "method": "POST"
        },
        "update": {
          "name": "update",
          "description": "Update a Message by ID",
          "path": "/:id",
          "method": "PUT"
        },
        "delete": {
          "name": "delete",
          "description": "Delete a Message by ID",
          "path": "/:id",
          "method": "DELETE"
        }
      }
    }
  }
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
