/* eslint-disable @typescript-eslint/no-var-requires */

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-08-09T13:02:02.856Z
 * Framework: vite
 * Output: src/
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "example": {
      "name": "example",
      "description": "",
      "path": "/example",
      "actions": {
        "health": {
          "name": "health",
          "description": "",
          "path": "/",
          "method": "GET"
        }
      }
    }
  }
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
